export const mockJWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWQiOiJhYmMxMjMiLCJmdWxsX25hbWUiOiJNci5XaGlza2VycyIsImVtYWlsIjoibXJ3aGlza2Vyc0BleGFtcGxlLmNvbSIsImlhdCI6MTUxNjIzOTAyMn0.w2-Ea4CG_YlgbXboioMuLwaj3PHkrZzhZOJheJAcBu8"
